#! /usr/bin/env node
// @ts-check
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {cwd} from 'node:process';
import path from 'node:path';
import {checks} from '../build/checks/index.js';

const STARTING_HEADING_DEPTH = 3;
export const AUTO_CHECKER_FILE = fileURLToPath(new URL('../docs/_includes/auto-checker.md', import.meta.url));

const header = `
{% comment %}
Don't edit this file directly! It was automatically generated by scripts/document-checks.js.
{% endcomment %}
`.trimStart();

/**
 * @typedef {import('../src/checks/index.ts').CheckGroup} CheckGroup
 */

/**
 * @param {CheckGroup | CheckGroup[]} checks
 */
function documentChecks(checks, depth = 0) {
	let buffer = '';

	if (Array.isArray(checks)) {
		for (const check of checks) {
			buffer += '#'.repeat(depth + STARTING_HEADING_DEPTH);
			buffer += ` ${check.name}`;
			buffer += '\n\n';
			buffer += documentChecks(check, depth);
			buffer += '\n';
		}

		return buffer;
	}

	if (depth > 0) {
		buffer += '  '.repeat((depth - 1) * 4);
		buffer += `* **${checks.name}**`;

		if (checks.description) {
			buffer += `: ${checks.description}`;
		}

		buffer += '\n';
	}

	for (const child of checks.children) {
		if ('children' in child) {
			buffer += documentChecks(child, depth + 1);
		} else {
			buffer += ' '.repeat(depth * 4);
			buffer += `* **${child.name}**: ${child.description}\n`;
		}
	}

	return buffer;
}

/**
 * @param {CheckGroup | CheckGroup[]} checks
 */
export function createAutoCheckerFile(checks) {
	return header + '\n' + documentChecks(checks);
}

writeFileSync(AUTO_CHECKER_FILE, createAutoCheckerFile(checks));
// eslint-disable-next-line no-console
console.log('Updated docs saved to', path.relative(cwd(), AUTO_CHECKER_FILE));
