title: "Discourse on Ghost"
remote_theme: just-the-docs/just-the-docs
search_enabled: false
baseurl: /discourse-on-ghost
permalink: pretty
color_scheme: dog
aux_links:
  "GitHub": https://github.com/vikaspotluri123/discourse-on-ghost
aux_links_new_tab: true
last_edit_timestamp: true
last_edit_timestamp_format: "%b %e %Y"
gh_edit_link: true
gh_edit_link_text: Suggest changes to this page on GitHub
gh_edit_repository: https://github.com/vikaspotluri123/discourse-on-ghost
gh_edit_view_mode: tree
gh_edit_branch: master
gh_edit_source: docs
plugins:
 - jekyll-seo-tag
kramdown:
  parse_block_html: true


# Things you can enable when working locally
# theme: just-the-docs
